backend:
  name: git-gateway
  repo: AppCivico/prep-web # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  -
    label: "Saiba Tudo"
    name: "Saiba Tudo"
    folder: "content/saiba-tudo"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      -
        label: "Dúvida"
        name: "title"
        widget: "string"
        tagname: "h3"
        pattern: ['.{3,40}', "Must have between 3 and 40 characters"]
      -
        label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]" # date sample 2018-03-06T14:48:47-03:00
      -
        label: "layout"
        name: "layout"
        widget: "hidden"
        default: "none"
      -
        label: "type"
        name: "type"
        widget: "hidden"
        default: "saiba-tudo"
      -
        label: "Resposta"
        name: "body"
        widget: "markdown"
      -
        label: "Ordem"
        name: "weight"
        widget: "number"
        default: 1
        valueType: "int"
        min: 0

  - label: "Dúvidas (Principal)"
    name: "duvidas-main"
    create: false # Allow users to create new documents in this collection
    delete: false # Allow users to delete documents in this collection
    files:
      - label: "Texto principal"
        name: "main-text"
        file: "content/duvidas.md"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Data", name: "date", widget: "datetime"}
          - {label: "layout", name: "layout", widget: "hidden", default: "duvidas"}
          - {label: "type", name: "type", widget: "hidden", default: "page"}
          - {label: "url", name: "url", widget: "hidden", default: "/duvidas"}
          - {label: "weight", name: "weight", widget: "hidden", default: "1"}
          - {label: "draft", name: "draft", widget: "hidden", default: "false"}
          - {label: "Texto", name: "body", widget: "markdown"}

# Social
  -
    label: "Redes sociais"
    name: "redes-sociais"
    files:
      -
        label: "Redes sociais"
        name: "items"
        file: "data/socialMedia.yml"
        fields:
          -
            label: "Links"
            name: "list"
            allow_add: false
            widget: "list"
            required: true
            fields:
              -
                label: "Nome"
                name: "name"
                widget: "string"
              -
                label: "Link"
                name: "url"
                widget: "string"
              -
                label: "Slug"
                name: "svg"
                widget: "hidden"

# Partners
  -
    label: "Parceiros"
    name: "parceiros"
    files:
      -
        label: "Parceiros"
        name: "partners"
        file: "data/partners.yml"
        fields:
          -
            label: "Parceiros"
            name: "list"
            allow_add: false
            widget: "list"
            required: true
            fields:
              -
                label: "Nome"
                name: "name"
                widget: "string"
              -
                label: "Css Class"
                name: "cssClass"
                widget: "hidden"
              -
                label: "Link"
                name: "url"
                widget: "string"

