backend:
  name: git-gateway
  repo: AppCivico/prep-web # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "duvidas" # Used in routes, e.g., /admin/collections/blog
    label: "Dúvidas" # Used in the UI
    folder: "content/duvidas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete documents in this collection
    slug: "{{ slug }}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Pergunta", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "layout", name: "layout", widget: "hidden", default: "none"}
      - {label: "type", name: "type", widget: "hidden", default: "duvidas"}
      - {label: "weight", name: "weight", widget: "hidden", default: "4"}
      - {label: "Resposta", name: "body", widget: "markdown"}

# Social
  -
    label: "Redes sociais"
    name: "redes-sociais"
    files:
      -
        label: "Redes sociais"
        name: "items"
        file: "data/socialMedia.yml"
        fields:
          -
            label: "Links"
            name: "list"
            allow_add: false
            widget: "list"
            required: true
            fields:
              -
                label: "Nome"
                name: "name"
                widget: "string"
              -
                label: "Link"
                name: "url"
                widget: "string"
              -
                label: "Slug"
                name: "svg"
                widget: "hidden"

# Partners
  -
    label: "Parceiros"
    name: "parceiros"
    files:
      -
        label: "Parceiros"
        name: "partners"
        file: "data/partners.yml"
        fields:
          -
            label: "Parceiros"
            name: "list"
            allow_add: false
            widget: "list"
            required: true
            fields:
              -
                label: "Nome"
                name: "name"
                widget: "string"
              -
                label: "Css Class"
                name: "cssClass"
                widget: "hidden"
              -
                label: "Link"
                name: "url"
                widget: "string"

